//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.AuthorBook = new HashSet<AuthorBook>();
            this.CollectionBook = new HashSet<CollectionBook>();
            this.GanreBook = new HashSet<GanreBook>();
            this.Library = new HashSet<Library>();
            this.TagBook = new HashSet<TagBook>();
        }
    
        public int idBook { get; set; }
        public string NameBook { get; set; }
        public string AboutBook { get; set; }
        public string ListValue { get; set; }
        public string PathFile { get; set; }
        public string FormatFile { get; set; }
        public string NameFile { get; set; }
        public byte[] ObjectFile { get; set; }
        public Nullable<System.DateTime> DateDowland { get; set; }
        public int RecomendedAge { get; set; }
        public Nullable<int> idImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorBook> AuthorBook { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionBook> CollectionBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GanreBook> GanreBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library> Library { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagBook> TagBook { get; set; }
    }
}
