//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Library_User
    {
        public long idUser { get; set; }
        public string NameBook { get; set; }
        public string FIO { get; set; }
        public byte[] ObjectFile { get; set; }
        public string FIO1 { get => $"{FIO}\n"; }
    }
}
