//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int idLibrary { get; set; }
        public long idUser { get; set; }
        public int idBook { get; set; }
        public Nullable<System.DateTime> DateHave { get; set; }
        public string Comment { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Userdb Userdb { get; set; }
    }
}
