//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local_Book_Information
    {
        public int idBook { get; set; }
        public string NameBook { get; set; }
        public string AboutBook { get; set; }
        public string ListValue { get; set; }
        public int RecomendedAge { get; set; }
        public byte[] BIT_IMAGE { get; set; }
        public string NameCollection { get; set; }
        public string Ganre { get; set; }
        public string Tag { get; set; }
        public string Author { get; set; }
    }
}
