//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userdb()
        {
            this.Library = new HashSet<Library>();
        }
    
        public long idUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronicym { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime Birthday { get; set; }
        public int idRole { get; set; }
        public Nullable<int> idClass { get; set; }
        public string Password { get; set; }
        public int idGender { get; set; }
        public bool CheckUser { get; set; }
        public Nullable<int> FullAge { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library> Library { get; set; }
        public virtual Role Role { get; set; }
    }
}
