//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_library1._1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_List_View
    {
        public Nullable<long> idUser { get; set; }
        public string FIO_USER { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string NameRole { get; set; }
        public string Password { get; set; }
        public string Class { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> CheckUser { get; set; }
    }
}
